### ISSUE TITLE
java.lang.IllegalStateException: Couldn't match exception header.

### ISSUE THREAD

**Issue by Dupleks** [square/spoon#312]
Hello, I faced this issue on Genymotion Galaxy Nexus - Android 4.3 - 720x1280. 
```
    at com.squareup.spoon.misc.StackTrace.acceptTrace(StackTrace.java:85)
    at com.squareup.spoon.misc.StackTrace.from(StackTrace.java:56)
    at com.squareup.spoon.DeviceTestResult$Builder.markTestAsFailed(DeviceTestResult.java:82)
    at com.squareup.spoon.SpoonTestRunListener.testFailed(SpoonTestRunListener.java:51)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:461)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:415)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:276)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:247)
    at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:522)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:388)
    at com.android.ddmlib.Device.executeShellCommand(Device.java:577)
    at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:263)
    at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:229)
    at com.squareup.spoon.SpoonDeviceRunner.main(SpoonDeviceRunner.java:381)
```
I am using spoon:spoon-gradle-plugin:1.0.3. Do you have any idea? 
Thanks a lot.

**Comment by edenman** [comment]
@Dupleks what's the error message?  looks like you chopped off the top of the stacktrace.

**Comment by Dupleks** [comment]
@edenman I take screenshot just in case https://monosnap.com/file/KjAKvJvMF83CgyG76WQ1LVwJb8hNjm 
```
java.lang.IllegalStateException: Couldn't match exception header.
    at com.squareup.spoon.misc.StackTrace.acceptTrace(StackTrace.java:85)
    at com.squareup.spoon.misc.StackTrace.from(StackTrace.java:56)
    at com.squareup.spoon.DeviceTestResult$Builder.markTestAsFailed(DeviceTestResult.java:82)
    at com.squareup.spoon.SpoonTestRunListener.testFailed(SpoonTestRunListener.java:51)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:461)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:415)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:276)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:247)
    at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:522)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:388)
    at com.android.ddmlib.Device.executeShellCommand(Device.java:577)
    at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:263)
    at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:229)
    at com.squareup.spoon.SpoonDeviceRunner.main(SpoonDeviceRunner.java:381)
```

**Comment by edenman** [comment]
Try spoon-gradle-plugin 1.0.4, I'm pretty sure this issue is fixed.

**Comment by Dupleks** [comment]
@edenman I updated spoon-gradle-plutin to 1.0.4 but I still see the same issue with another stacktrace:
```
java.lang.IllegalStateException: Couldn't match exception header.
    at com.squareup.spoon.misc.StackTrace.acceptTrace(StackTrace.java:85)
    at com.squareup.spoon.misc.StackTrace.from(StackTrace.java:56)
    at com.squareup.spoon.DeviceTestResult$Builder.markTestAsFailed(DeviceTestResult.java:90)
    at com.squareup.spoon.SpoonTestRunListener.testFailed(SpoonTestRunListener.java:51)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:461)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:415)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:276)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:247)
    at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
    at com.android.ddmlib.Device.executeShellCommand(Device.java:613)
    at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:260)
    at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:251)
    at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:159)
    at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:118)
    at com.squareup.spoon.SpoonRunner$run.call(null:-1)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
```

**Comment by daj** [comment]
I also hit this problem, and confirmed that it still happens on Spoon version 1.6.2.

![screen shot 2016-08-01 at 9 20 37 am](https://cloud.githubusercontent.com/assets/739125/17295257/39398540-57c9-11e6-891d-b478ca82cb5d.png)

It seems to be caused by printing out a very long assertion failure.  We have some code that collects up multiple assertion failures and prints them out at the end (similar to the JUnit [ErrorCollector](http://junit.org/junit4/javadoc/4.12/org/junit/rules/ErrorCollector.html) class).  Whenever multiple assertions occur, it causes Spoon to crash.

```
    public String getAssertionErrorMessages() {
        String assertionErrorMessages = null;
        if (hasAssertionErrors()) {
            StringWriter sw = new StringWriter();
            sw.append("\n**** " + assertionErrors.size() + " Assertion Errors Found ****\n");
            for (int i = 0; i < assertionErrors.size(); i++) {
                sw.append("\n--------- Failed Assertion # " + (i + 1) + " --------\n");
                AssertionError assertionError = assertionErrors.get(i);
                assertionError.printStackTrace(new PrintWriter(sw));
            }
            sw.append("\n----------------------------------");

            // Strip out these assertion error messages as they are redundant.
            assertionErrorMessages = sw.toString().replace("junit.framework.AssertionFailedError: ", "");
        }
        return assertionErrorMessages;
    }
```

**Comment by edenman** [comment]
@daj I bet it has something to do with the `.replace("junit.framework.AssertionFailedError: ", "")`.  `com.squareup.spoon.misc.StackTrace` has a particular format it expects, and you're manually manipulating the stacktrace string.  I won't have time to look at this anytime soon, but if you want to dig in, there's a unit test for this code you can run against your log output to see what's going wrong.

**Comment by daj** [comment]
Thanks for the pointer!  You're right, the issue is because we're manipulating the stack trace.  I wrote a unit test that reproduced the problem:
https://github.com/daj/spoon/commit/5bb4fdf3126ca529b38b3e989ce63c2f89ff25bb

Our manipulated stack trace fails to match the Spoon exception header validation in [StackTrace.java](https://github.com/square/spoon/blob/0e7361ea1c2926d3953a37a4f62357bc94dde3e2/spoon-runner/src/main/java/com/squareup/spoon/misc/StackTrace.java#L85):
```
  private static final Pattern HEADER = Pattern.compile("(?:Caused by: )?([^:]+)(?::( .*)?)?");
<snip>
    String header = messageParts.removeFirst();
    Matcher headerMatch = HEADER.matcher(header);
    if (!headerMatch.matches()) {
      throw new IllegalStateException("Couldn't match exception header.");
    }
```
It's unfortunate that this IllegalStateException stops the rest of the Spoon test report from being generated (or it stops the test suite from running there - I forget which), but I can see the argument for failing fast.

In the short term I'll probably try to massage our custom assertions so they match the stack trace format that Spoon accepts.  Thanks again!

**Comment by daj** [comment]
@edenman is there a reason that StackTrace _needs_ to parse the assertion text as an exception?  Is there some dependency on the exception that is important?  I might be missing something, but it seems that `HtmlUtils.processStackTrace` is the only place using the StackTrace methods, and it's only doing that to format the "   at " message, and insert "Caused by", and give the title special formatting.

Three suggestions I have:
 - Remove the parsing completely (probably too big a change for me).  Perhaps just treat the first line of text in the assertion failure/exception as the title?
 - Remove the `IllegalStateException`s in this class and default the StackTrace to display everything that came in, i.e. the whole thing gets printed like the title, so it probably all ends up in bold.
 - Keep the `IllegalStateException`s but add some more helpful text inside the exception, e.g. `Failed to parse the exception header.  Spoon assumes the assertion failure text is a standard format Java Exception.  If you have customized your assertion failures, you may need to make it match a standard format Java Exception.`

Would you recommend any of these approaches?

**Comment by JakeWharton** [comment]
There's two reasons:
* The data must be serialized across process boundaries
* The message is rendered separately in the output

**Comment by daj** [comment]
I could try and implement option 2 if either of you agree with it?  Right now users don't see any test results after an unparsable stack trace `IllegalStateException` happens, which feels like quite a disproportionate impact to me.

Regarding option 1, I wondered why it specifically needs to be parsed as a stack trace, rather than something more general like a List of Strings to be displayed.  I was originally thinking about people who customize their test failures with arbitrary text (we did this to provide a way of listing multiple assertion failures at once).  However, the source for [Assert](http://grepcode.com/file/repo1.maven.org/maven2/junit/junit/4.8.1/org/junit/Assert.java#Assert.fail%28java.lang.String%29) shows that even a `fail(String text)` results in a Throwable being generated, so assuming a stack trace seems sensible.
```
static public void More ...fail(String message) {
    throw new AssertionError(message == null ? "" : message);
}
```

**Comment by edenman** [comment]
@daj works for me, thanks!
